### ISSUE TITLE
Allow confik to read pyproject.toml

### ISSUE THREAD

**Issue by body20002** [LeOndaz/confik#1]
### I suggest adding a way to read configs values and settings from `pyproject.toml`

for example
```toml
# pyproject.toml
[tool.confik.env]
DEBUG = true
RUN_PYTEST = false
NonSensitiveValue = {value = 'VALUE', default = 'VALUE1', cast = str,}
EncryptedSensitiveValue = {encryption = 'algorithm'}

[tool.confik]
env_file = '.env'
env_parser = 'csv'
```
```bash
# .env
EncryptedSensitiveValue, AnotherEncryptedSensitiveValue
dadqe12314wsadfas, 2133adqw4r412321
```
```python
import confik
print(confik.get('DEBUG')) # >>> True
print(confik.get('EncryptedSensitiveValue')) # >>> Value
```
